version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: stemfounding-app
    container_name: stemfounding-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_DATABASE=STEMFounding
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    container_name: stemfounding-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: STEMFounding
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: